apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: cs3219-otot-a
  name: todo-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-frontend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
