version: '3.8'

services:
  database:
    image: postgres:14.0
    container_name: todo-database
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - todo-network
    logging:
      driver: journald
    expose:
      - '${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  backend:
    image: todo-backend:latest
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: todo-backend
    restart: always
    depends_on:
      - database
    networks:
      - todo-network
    logging:
      driver: journald
    expose:
      - '8000'
    environment:
      GO_ENV: production
      SERVER_PORT: 8000
      DB_HOST: todo-database
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSLMODE: disable

  frontend:
    image: todo-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: todo-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - todo-network
    logging:
      driver: journald
    ports:
      - '80:80'
    environment:
      BASE_SERVER_URL: ${BASE_SERVER_URL}

networks:
  todo-network:
