# To build a Docker image from this file, run:
# docker build -f Dockerfile-frontend -t todo-frontend .

# Base image
FROM node:14.18.0 AS build

# Copy source code into build container
WORKDIR /source
COPY todo-frontend .

# Install dependencies
RUN yarn install --frozen-lockfile

# Build the application
RUN yarn build

# Base image for final image
FROM nginx:1.21

# Copy executable from build stage
WORKDIR /frontend
COPY --from=build /source/build .

# Delete NGINX defaults
RUN rm -f /etc/nginx/conf.d/* /etc/nginx/sites-enabled/*

# Copy NGINX configuration
COPY nginx/nginx.conf /etc/nginx
COPY nginx/sites-enabled/* /etc/nginx/sites-enabled/

# Copy template file for environment variable substitution
COPY env.template.js .

# Add a script to be executed every time the container starts
COPY entrypoint-scripts/frontend.sh /usr/bin/
RUN chmod +x /usr/bin/frontend.sh
ENTRYPOINT ["frontend.sh"]

# Expose port 80
EXPOSE 80

# Default command
CMD ["nginx", "-g", "daemon off;"]
