apiVersion: v1
kind: Service
metadata:
  namespace: cs3219-otot-a
  name: todo-backend
spec:
  type: ClusterIP
  selector:
    app: todo-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
