apiVersion: v1
kind: Service
metadata:
  namespace: cs3219-otot-a
  name: todo-database
spec:
  type: ClusterIP
  selector:
    app: todo-database
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
